### ISSUE TITLE
Is it a robot ?

### ISSUE THREAD

**Issue by sanguohot** [greymd/ojichat#1]
额，谁能用中文翻译一下，还和`日本女性`有关，难道我想歪了？

**Comment by bwangelme** [comment]
Please do not make noise in the repo of others.

请不要在他人的项目中制造噪音。

**Comment by greymd** [comment]
> Is it a robot ?

@sanguohot chan, 非常感谢你的问题ヨ😘💕😆💗
这只是一个显示随机固定消息的程序😎😄

> 额，谁能用中文翻译一下，还和日本女性有关，难道我想歪了？

顺便问一下，为什么我们下次不吃午饭呢❓💖
这只是一个笑话，哈哈😃✋😂🎵
