### ISSUE TITLE
ojichat in WASM

### ISSUE THREAD

**Issue by Lesmiscore** [greymd/ojichat#25]
ojichatに感銘を受けたので、ノリでWeb上で動くようにしてみました。
WASMなのでローカルで動作します。
https://nao20010128nao.github.io/ojichat-wasm/

もし良ければWikiの関連ツール等のコーナーに追加してもらえませんか?

**Comment by greymd** [comment]
@nao20010128nao チャン、WASMで動くようにしてくれて、オジサン、うれしいぞ❗😍

...っと、実はwasm実装は既出ではありますが（[ojichat-web](https://github.com/syumai/ojichat-web)）、各パラメータ指定できるのいいですね！
wikiに記載しておきました。
